// put all action constants here
const SEARCH_GITHUB_REPO = 'SEARCH_GITHUB_REPO';
const SEARCH_GITHUB_REPO_SUCCESS = 'SEARCH_GITHUB_REPO_SUCCESS';
const SEARCH_GITHUB_REPO_ERROR = 'SEARCH_GITHUB_REPO_ERROR';

const actionTypes = {
  SEARCH_GITHUB_REPO,
  SEARCH_GITHUB_REPO_ERROR,
  SEARCH_GITHUB_REPO_SUCCESS
};

export default actionTypes;