// put all action constants here
const SEARCH_GITHUB_REPO = 'SEARCH_GITHUB_REPO';
const SEARCH_GITHUB_REPO_SUCCESS = 'SEARCH_GITHUB_REPO_SUCCESS';
const SEARCH_GITHUB_REPO_ERROR = 'SEARCH_GITHUB_REPO_ERROR';

// search action types
const SEARCH_ONCHANGE_TEXT = 'SEARCH_ONCHANGE_TEXT';
const SEARCH_ONCHANGE_TEXT_SUCCESS = 'SEARCH_ONCHANGE_TEXT_SUCCESS';
const SEARCH_ONCHANGE_TEXT_ERROR = 'SEARCH_ONCHANGE_TEXT_ERROR';

const actionTypes = {
  SEARCH_GITHUB_REPO,
  SEARCH_GITHUB_REPO_ERROR,
  SEARCH_GITHUB_REPO_SUCCESS,
  SEARCH_ONCHANGE_TEXT,
  SEARCH_ONCHANGE_TEXT_SUCCESS,
  SEARCH_ONCHANGE_TEXT_ERROR,
};

export default actionTypes;