fastlane_version '2.105.2'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/name.xcodeproj')
    gym(scheme: 'name', project: './ios/name.xcodeproj')
  end
end

platform :android do
  # Android Lanes
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'incrementVersionCode', project_dir: 'android/')
    bumpup_minor
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
  desc 'Build beta android'
  lane :beta do
    build
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode and versionName')
    push_to_git_remote
  end
  private_lane :bumpup_minor do
    # need android_versioning plugin
    increment_version_name(app_project_dir: '**/app', bump_type: 'minor')
  end
end
